---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: microservice-a
  annotations:
    tekton.dev/docker-0: https://harbor.34.84.199.182.nip.io/v2/
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-a
  namespace: microservice-a
secrets:
- name: harbor-credentials
